// <auto-generated />
using System;
using ContactManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContactManager.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Friend"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Acquintance"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Family"
                        });
                });

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CategoryId = 1,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1507),
                            Email = "jilmehta52@gmail.com",
                            FirstName = "Jil",
                            LastName = "Mehta",
                            Organization = "Yahoo",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 2,
                            CategoryId = 1,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1548),
                            Email = "nilmehta52@gmail.com",
                            FirstName = "Nil",
                            LastName = "Mehta",
                            Organization = "Google",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 3,
                            CategoryId = 1,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1551),
                            Email = "nachiketamehta52@gmail.com",
                            FirstName = "Nachiketa",
                            LastName = "Mehta",
                            Organization = "Facebook",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 4,
                            CategoryId = 1,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1553),
                            Email = "ajp52@gmail.com",
                            FirstName = "Arjun",
                            LastName = "Pathak",
                            Organization = "Yandex",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 5,
                            CategoryId = 2,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1555),
                            Email = "dewangiben@gmail.com",
                            FirstName = "Dewangi",
                            LastName = "Pathak",
                            Organization = "Baidu",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 6,
                            CategoryId = 2,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1558),
                            Email = "llbbhavya@gmail.com",
                            FirstName = "Bhavya",
                            LastName = "Dave",
                            Organization = "RSS",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 7,
                            CategoryId = 2,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1560),
                            Email = "zansikirani@gmail.com",
                            FirstName = "Bhakti",
                            LastName = "Dave",
                            Organization = "Zhansi",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 8,
                            CategoryId = 2,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1563),
                            Email = "itmeab@gmail.com",
                            FirstName = "Aakangsha",
                            LastName = "Borisagar",
                            Organization = "GujjuGarba",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 9,
                            CategoryId = 3,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1565),
                            Email = "bbdm@gmail.com",
                            FirstName = "Bhaumik",
                            LastName = "Prajapati",
                            Organization = "IndianOcean",
                            Phone = "647-832-1825"
                        },
                        new
                        {
                            ContactId = 10,
                            CategoryId = 3,
                            DateAdded = new DateTime(2022, 10, 1, 10, 34, 25, 361, DateTimeKind.Local).AddTicks(1567),
                            Email = "prpjdksh@gmail.com",
                            FirstName = "Prajapati",
                            LastName = "Daksh",
                            Organization = "Shrushti",
                            Phone = "647-832-1825"
                        });
                });

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.HasOne("ContactManager.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
